version: '3.8'

services:
  portainer:
    image: 'portainer/portainer-ce:2.17.0-alpine'
    container_name: 'portainer-app'
    ports:
    # - '0.0.0.0:8000:8000'
    # - '0.0.0.0:9443:9443'
     - '0.0.0.0:9000:9000'
    volumes:
      - '/hostPath/docker.sock:/var/run/docker.sock'
      - '/hostPath/data:/data'
    restart: 'unless-stopped'