version: '3.9'

services:
  app:
    image: portainer/agent:2.18.4-alpine
    volumes:
      - $(pwd)/docker.sock:/var/run/docker.sock
      - /:/host
      - $(pwd)/docker_volumes:/var/lib/docker/volumes
      - $(pwd)/lib_data:/data
    environment:
      - EDGE_INSECURE_POLL=1
      - EDGE=1
      - EDGE_ID=
      - EDGE_KEY=
      - AGENT_CLUSTER_ADDR=tasks.portainer-stack_app
    networks:
      - portainer-agent-net
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

networks:
  portainer-agent-net:
    name: portainer-agent-net
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/28
