version: '3.9'

services:
  app:
    image: portainer/agent:2.18.4-alpine
    ports:
      - '9001:9001'
    volumes:
      - $(pwd)/docker.sock:/var/run/docker.sock
      - $(pwd)/docker_volumes:/var/lib/docker/volumes
    networks:
      - portainer-agent-net
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

networks:
  portainer-agent-net:
    name: portainer-agent-net
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/28
